# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('on', 'ON'), ('off', 'OFF')], default='off', max_length=8),
        ),
    ]
