# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_auto_20160725_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='sensor',
            field=models.CharField(default='sensor', max_length=128),
            preserve_default=False,
        ),
    ]
